<?php

namespace Tests\Repositories;

use AlanGiacomin\LaravelBasePack\Models\Contracts\IModel;
use AlanGiacomin\LaravelBasePack\Repositories\Repository;

class RepositoryTestable extends Repository
{
    public function default(bool $allowNull = true): ?static
    {
        return parent::default($allowNull); // TODO: Change the autogenerated stub
    }

    public function findById(int $id): ?IModel
    {
        // TODO: Implement findById() method.
    }
}
