<?php

namespace App\Commands;

use AlanGiacomin\LaravelBasePack\Commands\CommandHandler;
use App\Events\AzioneFatta;
use Illuminate\Support\Facades\Log;

class EseguiAzioneHandler extends CommandHandler
{
    public EseguiAzione $command;

    public function execute()
    {
        Log::debug('STO ESEGUENDO FAI AZIONE');
        $this->publish(new AzioneFatta());
    }

    public function getResponse(): object|string|null
    {
        return parent::getResponse(); // TODO: Change the autogenerated stub
    }
}
