remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
nav:
    -   text: "Home"
        url: "/docs/index.md"
    -   text: "Introduzione"
        url: "/docs/index.md"
    -   text: "Guida"
        url: "/docs/guida.md"
