name: Set PR title

on:
    pull_request:
        types:
            -   opened

permissions:
    pull-requests: write

jobs:
    set-title:
        runs-on: ubuntu-latest
        if: github.actor != 'dependabot[bot]'
        steps:
            -   name: Set PR title
                uses: actions/github-script@v7
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: |
                        const { owner, repo, number: pull_number } = context.issue;
                        const pr = context.payload.pull_request;

                        let title = pr.title || '';
                        if (/^\d+\.x$/.test(pr.base.ref)) {
                            title = `[${pr.base.ref}] ${title}`;
                        }

                        await github.rest.pulls.update({
                            owner,
                            repo,
                            pull_number,
                            title,
                            body: pr.body || ''
                        });
